version: '3.8'

services:
  app:
    build: ./
    command: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data